x-default-isaac-lab-volumes:
  &default-isaac-lab-volumes
    # These volumes follow from this page
    # https://docs.omniverse.nvidia.com/app_isaacsim/app_isaacsim/install_faq.html#save-isaac-sim-configs-on-local-disk
    - type: volume
      source: isaac-cache-kit
      target: /isaac-sim/kit/cache
    - type: volume
      source: isaac-cache-ov
      target: /root/.cache/ov
    - type: volume
      source: isaac-cache-pip
      target: /root/.cache/pip
    - type: volume
      source: isaac-cache-gl
      target: /root/.cache/nvidia/GLCache
    - type: volume
      source: isaac-cache-compute
      target: /root/.nv/ComputeCache
    - type: volume
      source: isaac-logs
      target: /root/.nvidia-omniverse/logs
    - type: volume
      source: isaac-carb-logs
      target: /isaac-sim/kit/logs/Kit/Isaac-Sim
    - type: volume
      source: isaac-data
      target: /root/.local/share/ov/data
    - type: volume
      source: isaac-docs
      target: /root/Documents
      # These volumes allow X11 Forwarding
    # - type: bind
      # source: /tmp/.X11-unix
      # target: /tmp/.X11-unix
    - type: bind
      source: ${HOME}/.Xauthority
      target: /root/.Xauthority
    - type: bind
      source: ../
      target: /workspace/isaac_rover/
    - type: volume
      source: orbit-docs
      target: /workspace/orbit/docs/_build
    - type: volume
      source: orbit-logs
      target: /workspace/orbit/logs
    - type: volume
      source: orbit-data
      target: /workspace/orbit/data_storage


x-default-isaac-lab-deploy:
  &default-isaac-lab-deploy
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: all
            capabilities: [ gpu ]


x-default-isaac-lab-enviroment:
  &default-isaac-lab-environment
    ISAAC_SIM_PATH: /isaac-sim
    DISPLAY: ${DISPLAY}
    OMNI_KIT_ALLOW_ROOT: 1
    ACCEPT_EULA: Y
    RMW_IMPLEMENTATION: rmw_fastrtps_cpp
    FASTRTPS_DEFAULT_PROFILES_FILE: /root/.ros/fastdds.xml
    CYCLONEDDS_URI: /root/.ros/cyclonedds.xml
    RLROVERLAB_PATH: /workspace/isaac_rover/
    PYTHONPATH: /workspace/isaac_rover:${PYTHONPATH}



services:
  rover-lab-base:
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        - ISAAC_SIM_VERSION=5.1.0
        - ISAAC_LAB_VERSION=2.3.0
        - ISAAC_SIM_PATH=/isaac-sim
        - USER_HOME=/root
    image: rover-lab-base
    container_name: rover-lab-base
    environment: *default-isaac-lab-environment
    volumes: *default-isaac-lab-volumes
    network_mode: host
    deploy: *default-isaac-lab-deploy
    entrypoint: bash
    stdin_open: true
    tty: true

  rover-lab-ros2:
    env_file:
      - .env.ros2
    build:
      context: ../
      dockerfile: docker/Dockerfile.ros2
      args:
        - USER_HOME=/root
        - ISAAC_SIM_PATH=/isaac-sim
    image: rover-lab-ros2
    container_name: rover-lab-ros2
    environment: *default-isaac-lab-environment
    volumes: *default-isaac-lab-volumes
    network_mode: host
    deploy: *default-isaac-lab-deploy
    entrypoint: bash
    stdin_open: true
    tty: true


volumes:
  isaac-cache-kit:
  isaac-cache-ov:
  isaac-cache-pip:
  isaac-cache-gl:
  isaac-cache-compute:
  isaac-logs:
  isaac-carb-logs:
  isaac-data:
  isaac-docs:
  orbit-docs:
  orbit-logs:
  orbit-data:
