ARG ISAAC_SIM_VERSION
FROM nvcr.io/nvidia/isaac-sim:${ISAAC_SIM_VERSION}

# Set default RUN shell to bash
SHELL ["/bin/bash", "-c"]

ARG ISAAC_SIM_PATH
# Set environment variables
ENV LANG=C.UTF-8
ENV DEBIAN_FRONTEND=noninteractive
ENV ISAAC_LAB_PATH=/workspace/isaac_lab
ENV ROVER_LAB_PATH=/workspace/isaac_rover

# Install dependencies and remove cache
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    cmake \
    curl \
    git \
    libglib2.0-0 \
    ncurses-term && \
    apt -y autoremove && apt clean autoclean && \
    rm -rf /var/lib/apt/lists/*

# Clone Isaac Lab
RUN git clone https://github.com/isaac-sim/IsaacLab ${ISAAC_LAB_PATH}
RUN /bin/bash -c "cd ${ISAAC_LAB_PATH} && git checkout b4c9050"
# Create symlink to Isaac Sim
RUN ln -sf ${ISAAC_SIM_PATH} ${ISAAC_LAB_PATH}/_isaac_sim

# Install Isaac Lab
RUN ${ISAAC_LAB_PATH}/isaaclab.sh --install
# --extra

RUN echo "alias isaaclab=${ISAAC_LAB_PATH}/isaaclab.sh" >> ${HOME}/.bashrc && \
    echo "alias python=${ISAAC_SIM_PATH}/python.sh" >> ${HOME}/.bashrc && \
    echo "alias python3=${ISAAC_SIM_PATH}/python.sh" >> ${HOME}/.bashrc && \
    echo "alias pip='${ISAAC_SIM_PATH}/python.sh -m pip'" >> ${HOME}/.bashrc && \
    echo "alias pip3='${ISAAC_SIM_PATH}/python.sh -m pip'" >> ${HOME}/.bashrc && \
    echo "alias tensorboard='${ISAAC_SIM_PATH}/python.sh ${ISAAC_SIM_PATH}/tensorboard'" >> ${HOME}/.bashrc && \
    echo "export TZ=$(date +%Z)" >> ${HOME}/.bashrc \
    echo "export TZ=$(date +%Z)" >> ${HOME}/.bashrc

# Set working directory
WORKDIR ${ROVER_LAB_PATH}
