seed: 42

# Models are instantiated using skrl's model instantiator utility
# https://skrl.readthedocs.io/en/develop/modules/skrl.utils.model_instantiators.html
models:
  separate: False
  policy:
    type: "DeterministicPolicyConv"
    params:
      mlp_input_size: 5
      mlp_layers: [256, 160, 128]
      mlp_activation: "leaky_relu"
      encoder_layers: [8, 16, 32, 64]
      encoder_activation: "leaky_relu"
  target_policy:
    type: "DeterministicPolicyConv"
    params:
      mlp_input_size: 5
      mlp_layers: [256, 160, 128]
      mlp_activation: "leaky_relu"
      encoder_layers: [8, 16, 32, 64]
      encoder_activation: "leaky_relu"
  critic_1:
    type: "CriticConv"
    params:
      mlp_input_size: 5
      mlp_layers: [256, 160, 128]
      mlp_activation: "leaky_relu"
      encoder_layers: [8, 16, 32, 64]
      encoder_activation: "leaky_relu"
  critic_2:
    type: "CriticConv"
    params:
      mlp_input_size: 5
      mlp_layers: [256, 160, 128]
      mlp_activation: "leaky_relu"
      encoder_layers: [8, 16, 32, 64]
      encoder_activation: "leaky_relu"
  target_critic_1:
    type: "CriticConv"
    params:
      mlp_input_size: 5
      mlp_layers: [256, 160, 128]
      mlp_activation: "leaky_relu"
      encoder_layers: [8, 16, 32, 64]
      encoder_activation: "leaky_relu"
  target_critic_2:
    type: "CriticConv"
    params:
      mlp_input_size: 5
      mlp_layers: [256, 160, 128]
      mlp_activation: "leaky_relu"
      encoder_layers: [8, 16, 32, 64]
      encoder_activation: "leaky_relu"


#   learning_rate_scheduler: "KLAdaptiveRL"
agent:
  actor_learning_rate: 1.e-4
  critic_learning_rate: 1.e-4
  batch_size: 4096
  #learning_rate_scheduler: "None"
  #learning_rate_scheduler_kwargs: null
  #state_preprocessor: "None"
  #state_preprocessor_kwargs: null
  #value_preprocessor: "None"
  #value_preprocessor_kwargs: null
  entropy_learning_rate: 5.e-3
  random_timesteps: 0
  learning_starts: 0

  #rewards_shaper_scale: null
  # logging and checkpoint
  experiment:
    directory: "rover"
    experiment_name: ""
    write_interval: 40
    checkpoint_interval: 400
    wandb: True             # whether to use Weights & Biases

trainer:
  timesteps: 200000
  batch_size: 4096
